---
- name: BACK UP THE IFCFG FILES
  hosts: all
  become: yes
  
  tasks:
  - name: create a backup copy of ifcfg-ens192
    copy:
      src: /etc/sysconfig/network-scripts/ifcfg-ens192
      dest: /etc/sysconfig/network-scripts/backup-ens192
      
  - name: create a backup copy of ifcfg-ens224
    copy:
      src: /etc/sysconfig/network-scripts/ifcfg-ens224
      dest: /etc/sysconfig/network-scripts/backup-ens224
