---
- name: BACK UP THE IFCFG FILES
  hosts: all
  become: yes
  
  tasks:
  - name: create a backup copy of ifcfg-eth0
    copy:
      src: /etc/sysconfig/network-scripts/ifcfg-eth0
      dest: /etc/sysconfig/network-scripts/backup-eth0
