---
- name: DISABLE SELINUX
  hosts: all
  become: yes
  
  tasks:
    - name: call selinux module
      selinux:
        state: disabled
      register: selinux
      
    - name: show status
      debug:
        var: selinux
