---
- name: STOPR AND DISABLE FIREWALLD SERVICE
  hosts: all
  become: yes
  
  tasks:
    - name: stop the service
      firewalld:
        service: https
        permanent: yes
        state: disabled
