---
- name: DISABLE SELINUX AND REBOOT
  hosts: all
  become: yes
  
  tasks:
    - name: disable selinux
      selinux:
        state: disabled
      register: selinux
      
    - name: show status
      debug:
        var: selinux.state
        
    - name: call reboot module
      reboot:
