---
- name: INSTALL MULTIPLE PACKAGES
  hosts: all
  become: yes
  
  tasks: 
    - name: install packages with yum
      yum:
        name:
          - net-tools
          - wget
          - perl
        state: present
        update_cache: yes
      register: results
      
    - name: display results if packages were installed
      debug:
        var: results
      when: results is changed
