---
- name: INSTALL HTOP
  hosts: all
  become: yes
  
  tasks:
    - name: install htop using the yum module
      yum:
        name: htop
        state: present
      register: results
      
    - name: display results
      debug:
        var: results
      when: results is changed
