---
- name: INSTALL MULTIPLE PACKAGES
  hosts: all
  become: yes
  
  tasks: 
    - name: install packages with yum
      yum:
        name:
          - rabbitmq-server
          - wget
          - memcached
          - nginx
          - ansible
          - rh-git29
          - rh-postgressql10
          - rh-python36
        state: present
        disable_gpg_check: yes
        update_cache: yes
      register: results
      
    - name: display results if packages were installed
      debug:
        var: results
      when: results is changed
