---
- name: INSTALL POSTGRESQL
  hosts: all
  become: yes
  
  tasks:
    - name: downloard postgresql rpm
      yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present
        disable_gpg_check: yes
        
    - name: install postgresql11
      yum:
        name: postgresql11-server
        state: present
