---
- name: INSTALL EPEL REPOSITORY
  hosts: all
  become: yes
  
  tasks:
    - name: download latest epel repo from fedoraproject.org
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      register: results
      
    - name: display results
      debug:
        var: results
      when: results is changed
      
    - name: display installed repositories
      command: yum repolist
      register: repolist
      
    - name: display repolist
      debug:
        var: repolist
