---
- name:
  hosts: all
  become: yes
  
  tasks:
    - name:
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      register: results
      
    - name:
      debug:
        var: results
