---
- name: RUN IP LINK SHOW COMMAND
  hosts: all
  become: yes
  
  tasks:
  - name: run the ip link show command
    command: ip link show
    register: iplink
    
  - name: show the results
    debug: 
      var: iplink
