---
- name: UPDATE ALL PACKAGES WITH YUM
  hosts: all
  become: yes
  
  tasks:
  - name: apply yum updates
    yum:
      name: '*'
      state: latest
    register:
      task_result
      
  - name: print results if updates were made
    debug:
      var: task_result
    when: task_result is changed
