---
- name: UPDATE HOSTS FILE
  hosts: all
  become: yes
  
  tasks:
    - name: add a line to the hosts file if it does not exist
      lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.interface }}  AWX"
        create: yes
      register: hostsfile
      
    - name: display hosts file
      debug:
        var: hostsfile
